trigger: none

parameters:
- name: vm_image
  default: 'ubuntu-20.04'
  values:
  - 'ubuntu-20.04'
  displayName: Azure DevOps Agent OS Version
- name: terraform_directory
  default: '$(Build.Repository.LocalPath)/terraform'
  displayName: Path to the Terraform Directory

variables:
  tfvars_file_name: 'env_dev.tfvars'
  tfvars_file_secure: 'env_dev_sec_tfvars'
  tfvars_file_secure_backend: 'env_dev_backend_sec_tfvars'

stages:
- stage: create_terraform_docs
  pool:
    vmImage: ${{ parameters.vm_image }}
  jobs:
  - job: create_terraform_docs
    displayName: create terraform documentation
    steps:
    - checkout: self
      persistCredentials: true
      clean: true

    - template: ../templates/steps/terraform-docs.yml
      parameters:
        terraform_directory: ${{ parameters.terraform_directory }}

    - template: ../templates/steps/git_commit_changes.yml
      parameters:
        commit_message: "chore(terraform docs): :arrow_up:  update terraform infrastructure docs [skip ci]"
